### PR TITLE
remove mirage-vnetif-stack: this has not been used anywhere

### PR DESCRIPTION
**Pull request by hannesm**
update test to not use the mirage-vnetif-stack

### CODE REVIEW

**Comment by hannesm** [comment]
I'm not sure about the test to be honest... it requires some cyclic "with-test" dependencies, and I'm not sure whether it is worth it to keep. thus I added a commit which removes the tests.

**Comment by MagnusS** [comment]
Initially this was quite useful to check that the backend worked and didn't deadlock with the timers in mirage-tcpip, but when I integrated the test with the tcpip-stack it needed a modified backend and stack:

https://github.com/mirage/mirage-tcpip/blob/main/test/vnetif_backends.ml
https://github.com/mirage/mirage-tcpip/blob/main/test/vnetif_common.ml

My plan was to move these back here, according [to this todo](https://github.com/mirage/mirage-tcpip/blob/main/test/vnetif_common.ml#L20) :-)

I think it's ok to remove this from this package for now if it doesn't have any users, but it would be very useful to still have a way to test that changes to mirage-vnetif will work with mirage-tcpip.

**Comment by hannesm** [comment]
Thanks for your reply @MagnusS. I'm not sure what you have in mind in respect to "but it would be very useful to still have a way to test that changes to mirage-vnetif will work with mirage-tcpip"? To avoid dependency cycles and complexity, would it be sufficient to document that "please test changes by pinning mirage-vnetif and run the tcpip test suite"?

**Comment by MagnusS** [comment]
What would you prefer? I think you've done most of the recent releases. For PRs it's useful with something in CI, but I'm fine with a documentation note. Currently the project is mostly in maintenance mode, if we do substantial work on this later we can add some of this back (without the cyclic dependency).

**Comment by hannesm** [comment]
@MagnusS since I don't know how to setup such a CI -- now "OCaml-CI" is used, which is "zero configuration", and from the maintenance perspective, getting rid of mirage-vnetif-stack would be nice, I'd like to merge this PR, write some documentation, and move on :)

**Comment by MagnusS** [comment]
Sounds good to me!

**Pull request merged**
